spring:
  datasource:
    url: jdbc:mysql://192.168.20.79:3306/novel?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: Huawei@311
    driver-class-name: com.mysql.cj.jdbc.Driver

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.lx.novel_writing_backend.entity
  configuration:
    map-underscore-to-camel-case: true

jwt:
  secret: your-jwt-secret-key-at-least-32-characters-long
  expiration: 86400000  # 24小时
